---
- name: "Install certificate for {{ proxy_setup_internal_subdomain }}.kleinendorst.info"
  become: true
  ansible.builtin.command:
    cmd: "register_certbot_domain.sh {{ proxy_setup_internal_subdomain }}.kleinendorst.info"
    creates: "/etc/letsencrypt/live/{{ proxy_setup_internal_subdomain }}.kleinendorst.info" # The certificate directory
- name: Set Nginx configuration
  become: true
  ansible.builtin.template:
    src: nginx-configuration.conf.j2
    dest: "/etc/nginx/conf.d/{{ proxy_setup_internal_subdomain }}.conf"
    mode: '0644'
  notify: Restart Nginx
- name: Add entry in /etc/hosts
  become: true
  notify: Restart dnsmasq
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ansible_facts['default_ipv4']['address'] }} {{ proxy_setup_internal_subdomain }}.kleinendorst.info"
# It would be ideal if we could install a cloudflare public tunnel rule here but I can't see an Ansible module
# for this with a quick search. For now installation can be done manual (via the CloudFlare Zero Trust dashboard).
