---
- name: Install Snapcraft
  become: true
  ansible.builtin.apt:
    name: snapd
    state: present
- name: Install Snap Core
  become: true
  community.general.snap:
    name: core
    state: present
