---
collections:
  # from Ansible Galaxy
  # See: https://galaxy.ansible.com/ui/repo/published/devsec/hardening/
  - name: devsec.hardening
    version: 9.0.1
roles:
  - name: singleplatform-eng.users
    version: v1.2.6
