---
- name: Install the container
  become: true
  community.docker.docker_container:
    name: watchtower
    image: "containrrr/watchtower:latest"
    env:
      # WATCHTOWER_POLL_INTERVAL: "10800" # 3 hours
      WATCHTOWER_POLL_INTERVAL: "60"
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
    restart_policy: always
