---
- name: Install the container
  become: true
  community.docker.docker_container:
    name: cyberchef
    # ⬇️ Not the official image but this one is build for arm64
    image: mpepping/cyberchef:latest
    image_name_mismatch: recreate
    ports:
      - "127.0.0.1:8088:8000/tcp"
    restart_policy: always
- name: Include proxy-setup role
  ansible.builtin.include_role:
    name: proxy-setup
  vars:
    proxy_setup_internal_port: 8088
    proxy_setup_internal_subdomain: cyberchef
