---
- name: Install the container
  become: true
  community.docker.docker_container:
    name: cyberchef
    # ⬇️ Not the official image but this one is build for arm64
    image: mpepping/cyberchef:latest
    image_name_mismatch: recreate
    ports:
      - "127.0.0.1:8088:8000/tcp"
    restart_policy: always
- name: Include simple-reverse-proxy role
  ansible.builtin.include_role:
    name: simple-reverse-proxy
  vars:
    simple_reverse_proxy_internal_port: 8088
    simple_reverse_proxy_internal_subdomain: cyberchef
