---
- name: Log into private GitHub registry
  become: true
  community.docker.docker_login:
    registry_url: ghcr.io
    username: "{{ github_registry_user }}"
    password: "{{ github_registry_token }}"
- name: Install the container
  become: true
  community.docker.docker_container:
    name: wedding-server
    image: "ghcr.io/kleinendorst/wedding:{{ versions.wedding }}"
    ports:
      - "127.0.0.1:3001:3000/tcp"
    env:
      DATABASE_HOST: 'postgres.kleinendorst.info'
      DATABASE_PORT: '5432'
      DATABASE_DBNAME: 'wedding'
      DATABASE_USER: "{{ postgres.user }}"
      DATABASE_PASSWORD: "{{ postgres.password }}"
      SESSION_SECRET: "{{ wedding_env.secret }}"
      NODE_ENV: 'production'
      WEDDING_FULL_ACCESS_CODE: "{{ wedding_env.full_access_code }}"
      WEDDING_NIGHT_ACCESS_CODE: "{{ wedding_env.night_access_code }}"
    restart_policy: always
