---
# TODO: Not tested yet... see versions.yml
- name: Reinstall cloudflared
  become: true
  ansible.builtin.command:
    cmd: "bash -c 'cloudflared service uninstall && cloudflared service install {{ cloudflared_refresh_token }}'"
    creates: /etc/systemd/system/cloudflared.service
