---
# Still not tested yet. The problem is each time that the service is installed but not actived
# after which I manually need to start it.
- name: Reinstall cloudflared
  # Tried to use a block but this wouldn't work:
  # https://stackoverflow.com/questions/71578834/using-block-in-handler-ansible#answer-71583324
  ansible.builtin.include_tasks: tasks/reinstall-service.yml
