---
- name: Read local vault
  ansible.builtin.include_vars: vault.yml
- name: Create a new user
  ansible.builtin.include_role:
    name: user
  vars:
    username: cloudflare_ddns
    password: "{{ cloudflare_ddns_user_password }}"
