---
- include_vars: vault.yml
# TODO: Configure ZSH correctly by reasusing the zsh role by running the commands as the new user.
#       see: https://serverfault.com/questions/662443/running-ansible-task-as-a-specific-user
- name: Create a new user
  ansible.builtin.include_role:
    name: user
  vars:
    username: cloudflare_ddns
    password: "{{ cloudflare_ddns_user_password }}"
