---
- name: Include the Prometheus role
  ansible.builtin.include_role:
    name: prometheus.prometheus.prometheus
- name: Include simple-reverse-proxy role - Prometheus
  ansible.builtin.include_role:
    name: simple-reverse-proxy
  vars:
    simple_reverse_proxy_internal_port: 9090
    simple_reverse_proxy_internal_subdomain: prometheus
- name: Include the Prometheus - node exporter role
  ansible.builtin.include_role:
    name: prometheus.prometheus.node_exporter
- name: Include the Prometheus - alertmanager role
  ansible.builtin.include_role:
    name: prometheus.prometheus.alertmanager
- name: Include simple-reverse-proxy role - Prometheus
  ansible.builtin.include_role:
    name: simple-reverse-proxy
  vars:
    simple_reverse_proxy_internal_port: 9093
    simple_reverse_proxy_internal_subdomain: alertmanager
# region: Install Grafana
- name: Create a volume
  become: true
  community.docker.docker_volume:
    name: grafana_data
- name: Install the container
  become: true
  community.docker.docker_container:
    name: grafana-server
    image: "docker.io/grafana/grafana:{{ grafana_version }}"
    ports:
      - "127.0.0.1:3000:3000/tcp"
    mounts:
      - source: grafana_data
        target: /var/lib/grafana
    env:
      GF_INSTALL_PLUGINS: "grafana-clock-panel 2.1.8"
    restart_policy: always
- name: Include simple-reverse-proxy role
  ansible.builtin.include_role:
    name: simple-reverse-proxy
  vars:
    simple_reverse_proxy_internal_port: 3000
    simple_reverse_proxy_internal_subdomain: grafana
