---
- name: Include the Prometheus role
  ansible.builtin.include_role:
    name: prometheus.prometheus.prometheus
- name: Include the Prometheus - node exporter role
  ansible.builtin.include_role:
    name: prometheus.prometheus.node_exporter
- name: Include the Prometheus - alertmanager role
  ansible.builtin.include_role:
    name: prometheus.prometheus.alertmanager
