---
- name: Install the container
  become: true
  community.docker.docker_container:
    name: memos-server
    image: "neosmemo/memos:stable"
    image_name_mismatch: recreate
    env:
      MEMOS_DRIVER: 'postgres'
      MEMOS_DSN: "postgresql://{{ memos_postgres_user }}:{{ memos_postgres_password }}@postgres.kleinendorst.info:5432/memos"
    ports:
      - "127.0.0.1:5230:5230/tcp"
    restart_policy: always
- name: Include proxy-setup role
  ansible.builtin.include_role:
    name: proxy-setup
  vars:
    proxy_setup_internal_port: 5230
    proxy_setup_internal_subdomain: memos
