---
# Prometheus
prometheus_version: "{{ versions.monitoring.prometheus }}"
prometheus_targets:
  prometheus:
    - targets:
        - raspberry-pi-1.kleinendorst.info:9090
  node:
    - targets:
        - raspberry-pi-1.kleinendorst.info:9100
  grafana:
    - targets:
        - raspberry-pi-1.kleinendorst.info:3000
  postgres:
    - targets:
        - raspberry-pi-1.kleinendorst.info:9187
  cadvisor:
    - targets:
        - raspberry-pi-1.kleinendorst.info:8091
  docker:
    - targets:
        - raspberry-pi-1.kleinendorst.info:9323
prometheus_web_listen_address: 0.0.0.0:9090
prometheus_scrape_configs:
  - job_name: "prometheus"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/prometheus.yml"
  - job_name: "node"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node.yml"
  - job_name: "grafana"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/grafana.yml"
  - job_name: "postgres"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/postgres.yml"
  - job_name: "cadvisor"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/cadvisor.yml"
  - job_name: "docker"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/docker.yml"
prometheus_alert_rules: []
prometheus_alert_rules_files: []
# Node exporter
node_exporter_version: "{{ versions.monitoring.node_exporter }}"
node_exporter_enabled_collectors:
  - systemd
  - {"textfile": {"directory": "{{ node_exporter_textfile_dir }}"}}
  - processes
node_exporter_web_listen_address: 192.168.50.27:9100
# Grafana
grafana_username: grafana
