---
# Prometheus
prometheus_version: "2.54.1"
prometheus_targets:
  prometheus:
    - targets:
        - 127.0.0.1:9090
  node:
    - targets:
        - 127.0.0.1:9100
  grafana:
    - targets:
        - 127.0.0.1:3000
prometheus_scrape_configs:
  - job_name: "prometheus"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/prometheus.yml"
  - job_name: "node"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node.yml"
  - job_name: "grafana"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/grafana.yml"
prometheus_alertmanager_config:
  - static_configs:
      - targets:
          - 127.0.0.1:9093
# Node exporter
node_exporter_version: "1.8.2"
node_exporter_enabled_collectors:
  - systemd
  - {"textfile": {"directory": "{{ node_exporter_textfile_dir }}"}}
  - processes
# Alertmanager
alertmanager_version: "0.27.0"
# Telegram configuration inspired by this source:
# https://www.stranatesta.eu/tech/how-to-configure-prometheus-alertmanager-to-send-alerts-to-telegram/#configure-alertmanager
alertmanager_receivers:
  - name: telegram
    telegram_configs:
      - bot_token: "{{ telegram_bot_token }}"
        api_url: 'https://api.telegram.org'
        chat_id: "{{ telegram_chat_id }}"
        parse_mode: ''
alertmanager_route:
  receiver: telegram
# Grafana
grafana_version: "11.2.0"
grafana_username: grafana
