---
- name: Restart Nginx
  become: true
  ansible.builtin.systemd:
    name: nginx.service
    state: restarted
- name: Restart ufw
  become: true
  ansible.builtin.systemd:
    name: ufw.service
    state: restarted
- name: Reload systemd (daemon-reload)
  become: true
  become_user: "{{ pi_hole_username }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
