---
- name: Create portainer volume
  become: true
  community.docker.docker_volume:
    volume_name: portainer_data
- name: Install the container
  become: true
  community.docker.docker_container:
    name: portainer
    image: "portainer/portainer-ce:latest"
    image_name_mismatch: recreate
    ports:
      # - "127.0.0.1:9443:9443/tcp" # TCP port, not used
      # But the opened http port is only opened for "legacy reasons", see: https://docs.portainer.io/start/install-ce/server/docker/linux
      - "127.0.0.1:9000:9000/tcp"
    env:
      # See: https://docs.portainer.io/advanced/reverse-proxy/nginx
      VIRTUAL_HOST: portainer.kleinendorst.info
      VIRTUAL_PORT: '9000'
    mounts:
      - source: portainer_data
        target: /data
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
    restart_policy: always
- name: Include proxy-setup role
  ansible.builtin.include_role:
    name: proxy-setup
  vars:
    proxy_setup_internal_port: 9000
    proxy_setup_internal_subdomain: portainer
