---
- name: Create the compose project directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/changedetection"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: '0744'
- name: Create the compose project
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "/home/{{ ansible_user_id }}/changedetection/docker-compose.yaml"
    owner: "{{ ansible_user_id }}"
    mode: '0644'
- name: Create and start services
  become: true
  community.docker.docker_compose_v2:
    project_src: "/home/{{ ansible_user_id }}/changedetection/"
- name: Include simple-reverse-proxy role
  ansible.builtin.include_role:
    name: simple-reverse-proxy
  vars:
    simple_reverse_proxy_internal_port: 5000
    simple_reverse_proxy_internal_subdomain: changedetection
