---
- name: Create a volume
  become: true
  community.docker.docker_volume:
    name: changedetection_data
- name: Install the container
  become: true
  community.docker.docker_container:
    name: changedetection-server
    image: "docker.io/dgtlmoon/changedetection.io:{{ changedetection_version }}"
    ports:
      - "127.0.0.1:5000:5000/tcp"
    mounts:
      - source: changedetection_data
        target: /datastore
    restart_policy: always
- name: Include simple-reverse-proxy role
  ansible.builtin.include_role:
    name: simple-reverse-proxy
  vars:
    simple_reverse_proxy_internal_port: 5000
    simple_reverse_proxy_internal_subdomain: changedetection
