---
- name: Include user role
  ansible.builtin.include_role:
    name: user
  vars:
    user_username: "{{ changedetection_username }}"
    user_password: "{{ changedetection_password }}"
- name: Create the changedetection container
  ansible.builtin.include_role:
    name: podman-container
    apply:
      become: true
      become_user: "{{ changedetection_username }}"
  vars:
    podman_container_name: changedetection-server
    podman_container_image: docker.io/dgtlmoon/changedetection.io
    podman_container_tag: "{{ changedetection_version }}"
    podman_container_publish:
      - 127.0.0.1:5000:5000
    podman_simple_container_volumes:
      - name: changedetection_data
        mnt: /datastore
- name: Include simple-reverse-proxy role
  ansible.builtin.include_role:
    name: simple-reverse-proxy
  vars:
    simple_reverse_proxy_internal_port: 5000
    simple_reverse_proxy_internal_subdomain: changedetection
