---
# Inspired by this article: https://pimylifeup.com/raspberry-pi-dns-server/
- name: Install dnsmasq
  become: true
  ansible.builtin.apt:
    name: dnsmasq
    state: present
- name: Install configuration file
  become: true
  notify: Restart dnsmasq
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
