---
# Inspired by this article: https://pimylifeup.com/raspberry-pi-dns-server/
- name: Install dnsmasq
  become: true
  ansible.builtin.apt:
    name: dnsmasq
    state: present
- name: Install configuration file
  become: true
  notify: Restart dnsmasq
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
# This is a weird thing about my router. It wants to talk over https with the asusrouter.com name
# but this is not all that well documented. This added entry makes sure it can be resolved.
- name: Install the asusrouter.com domain in /etc/hosts
  become: true
  notify: Restart dnsmasq
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "192.168.50.1 asusrouter.com"
