---
- name: Create a volume for DNS data
  become: true
  community.docker.docker_volume:
    name: pihole_data
- name: Create a volume for Dnsmasq data
  become: true
  community.docker.docker_volume:
    name: dnsmasq_data
- name: Install the container
  become: true
  community.docker.docker_container:
    name: pi-hole
    image: "docker.io/pihole/pihole:{{ pi_hole_version }}"
    mounts:
      - source: pihole_data
        target: /etc/pihole
      - source: dnsmasq_data
        target: /etc/dnsmasq.d
    network_mode: host
    restart_policy: always
    env:
      TZ: 'Europe/Amsterdam'
      WEBPASSWORD: "{{ pi_hole_web_password }}"
      # VIRTUAL_HOST: 'pi-hole.kleinendorst.info'
      # FTLCONF_LOCAL_IPV4: "{{ ansible_facts['default_ipv4']['address'] }}"
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      DNSMASQ_USER: root
      DNSMASQ_LISTENING: all
      WEB_PORT: '8080'
- name: Include simple-reverse-proxy role
  ansible.builtin.include_role:
    name: simple-reverse-proxy
  vars:
    simple_reverse_proxy_internal_port: 8080
    simple_reverse_proxy_internal_subdomain: pi-hole
    simple_reverse_proxy_redirect_to: /admin
