---
- name: Install Cloudflared
  become: true
  notify: Reinstall cloudflared
  ansible.builtin.apt:
    deb: "https://github.com/cloudflare/cloudflared/releases/download/{{ versions.cloudflared }}/cloudflared-linux-arm64.deb"
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Install the Cloudflared tunnel as a systemd service
  become: true
  ansible.builtin.command:
    cmd: "cloudflared service install {{ cloudflared_refresh_token }}"
    creates: /etc/systemd/system/cloudflared.service
